#!/usr/bin/env bash
# setup-board.sh — github-workflow 보드 셋업 헬퍼.
#
# 하는 일:
#   1) 전제조건 점검 — gh 인증 + 'project' 스코프, jq.
#   2) org-scoped GitHub Project 생성(또는 기존 번호 재사용).
#   3) Status 단일선택 필드 옵션을 점검하고, 부족하면 UI 에서 맞출 항목을 안내.
#   4) 대상 repo 루트에 .github-workflow.config 작성(owner/number).
#
# 사용법:
#   bash setup-board.sh --owner <org-login> [--title "<title>"] [--repo <path>]
#   bash setup-board.sh --owner <org-login> --number <N> [--repo <path>]   # 기존 보드 사용
#
# 이 스킬은 org-scoped Project 만 지원한다(모든 GraphQL 이 organization(login) 가정).
# 상세: docs/board-setup.md
set -euo pipefail

# 스킬이 요구하는 Status 단일선택 옵션(순서 포함).
REQUIRED_STATUSES=(Backlog Ready "In progress" "In review" Approved Done)

OWNER=""
NUMBER=""
TITLE="GitHub Workflow Board"
REPO_DIR="$PWD"

die()  { printf '❌ %s\n' "$*" >&2; exit 1; }
info() { printf 'ℹ️  %s\n' "$*"; }
ok()   { printf '✅ %s\n' "$*"; }
warn() { printf '⚠️  %s\n' "$*" >&2; }

usage() {
  cat <<'EOF'
setup-board.sh — github-workflow 보드 셋업

Usage:
  bash setup-board.sh --owner <org-login> [--title "<title>"] [--repo <path>]
  bash setup-board.sh --owner <org-login> --number <N> [--repo <path>]

Options:
  --owner <org>    Project 을 소유한 organization login (필수)
  --number <N>     기존 Project 번호를 재사용(생략 시 새로 생성)
  --title <t>      새 Project 제목(기본: "GitHub Workflow Board")
  --repo <path>    .github-workflow.config 를 쓸 repo 루트(기본: 현재 디렉터리)
  -h, --help       이 도움말
EOF
}

while (( $# > 0 )); do
  case "$1" in
    --owner)  OWNER="${2:-}"; shift 2 ;;
    --number) NUMBER="${2:-}"; shift 2 ;;
    --title)  TITLE="${2:-}"; shift 2 ;;
    --repo)   REPO_DIR="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "알 수 없는 인자: '$1' (--help 참고)" ;;
  esac
done

# ── 1) 전제조건 ──────────────────────────────────────────────────────
command -v gh >/dev/null 2>&1 || die "gh CLI 가 필요합니다 (https://cli.github.com)."
command -v jq >/dev/null 2>&1 || die "jq 가 필요합니다."
gh auth status >/dev/null 2>&1 || die "gh 인증이 필요합니다: gh auth login"
if ! gh auth status 2>&1 | grep -q "project"; then
  die "gh 토큰에 'project' 스코프가 없습니다: gh auth refresh -s project"
fi
[[ -n "$OWNER" ]] || { usage; die "--owner <org-login> 는 필수입니다."; }
[[ -d "$REPO_DIR" ]] || die "--repo 경로가 디렉터리가 아닙니다: $REPO_DIR"

# ── 2) Project 생성 또는 재사용 ──────────────────────────────────────
if [[ -z "$NUMBER" ]]; then
  info "Project 생성 중: owner=${OWNER} title=\"${TITLE}\" ..."
  created=$(gh project create --owner "$OWNER" --title "$TITLE" --format json) \
    || die "Project 생성 실패 (org 권한·project 스코프 확인)."
  NUMBER=$(printf '%s' "$created" | jq -r '.number')
  [[ -n "$NUMBER" && "$NUMBER" != "null" ]] || die "생성된 Project 번호를 읽지 못했습니다."
  ok "Project 생성됨: #${NUMBER}"
else
  info "기존 Project 재사용: owner=${OWNER} number=#${NUMBER}"
fi

PROJECT_URL="https://github.com/orgs/${OWNER}/projects/${NUMBER}"

# ── 3) Status 필드 옵션 점검 ─────────────────────────────────────────
info "Status 필드 옵션 점검 중 ..."
fields_json=$(gh project field-list "$NUMBER" --owner "$OWNER" --format json 2>/dev/null) || fields_json=""
existing_opts=""
if [[ -n "$fields_json" ]]; then
  existing_opts=$(printf '%s' "$fields_json" \
    | jq -r '.fields[]? | select(.name=="Status") | .options[]?.name' 2>/dev/null || true)
fi

missing=()
for s in "${REQUIRED_STATUSES[@]}"; do
  if ! printf '%s\n' "$existing_opts" | grep -qxF "$s"; then
    missing+=("$s")
  fi
done

if (( ${#missing[@]} == 0 )); then
  ok "Status 필드에 필요한 옵션이 모두 존재합니다: ${REQUIRED_STATUSES[*]}"
else
  warn "Status 필드에 다음 옵션이 없습니다: ${missing[*]}"
  cat >&2 <<EOF
   GitHub Projects 의 빌트인 Status 옵션은 API 로 안정적으로 편집되지 않습니다.
   아래 보드의 Settings → Status 필드에서 옵션을 다음 6개로 맞춰 주세요(순서 포함):

     ${REQUIRED_STATUSES[*]}

   보드: ${PROJECT_URL}/settings
   상세: docs/board-setup.md §Status 필드 옵션
EOF
fi

# ── 4) .github-workflow.config 작성 ──────────────────────────────────
cfg="${REPO_DIR%/}/.github-workflow.config"
if [[ -f "$cfg" ]]; then
  warn "${cfg} 가 이미 존재합니다 — 덮어쓰지 않습니다. 아래 값을 확인하세요:"
  printf '   CLAUDE_PROJECT_OWNER=%q\n   CLAUDE_PROJECT_NUMBER=%q\n' "$OWNER" "$NUMBER" >&2
else
  cat > "$cfg" <<EOF
# github-workflow per-repo board config (generated by setup-board.sh)
CLAUDE_PROJECT_OWNER="${OWNER}"
CLAUDE_PROJECT_NUMBER=${NUMBER}
EOF
  ok "설정 파일 작성: ${cfg}"
  info ".gitignore 에 추가하려면: echo '.github-workflow.config' >> ${REPO_DIR%/}/.gitignore"
fi

echo ""
ok "보드 셋업 완료. 보드: ${PROJECT_URL}"
info "다음: 워크플로우 함수를 로드하고 사용하세요 —"
echo '       source "${CLAUDE_PLUGIN_ROOT}/scripts/github-workflow.sh"'
echo "       claude-board-status"
